spring:
  datasource:
    url: jdbc:h2:mem:cvs
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    database: h2
    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: true

  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftl

server:
  servlet:
    context-path: /api/v1/pdf-cv
app:
  image:
    base-path: src/main/resources/
    upload-path: images/
  style:
    base-path: src/main/resources/templates/