drop table if exists users cascade;

-- Create users table
create table users
(
    relevant_experience_years integer,
    id                        bigint generated by default as identity,
    email                     varchar(255) unique,
    first_name                varchar(255),
    image_path                varchar(255),
    last_name                 varchar(255),
    location                  varchar(255),
    mobile_phone_number       varchar(255),
    nationality               varchar(255),
    title                     varchar(255),
    password                  varchar(255),
    profession                varchar(255),
    summary                   varchar(255),
    primary key (id)
);

drop table if exists resumes cascade;

-- Create resumes table
create table resumes
(
    id          bigint generated by default as identity,
    resume_data json,
    user_id     bigint,
    primary key (id)
);

-- Insert user data
INSERT INTO USERS (relevant_experience_years, first_name, last_name, password, email, nationality, location, summary,
                   title, profession, mobile_phone_number, image_path)
VALUES (5,
        'John',
        'Doe',
        'securePassword',
        'john.doe@example.com',
        'US',
        'New York',
        'Experienced software engineer',
        'B. Eng.',
        'Software Engineer',
        '+1 123-456-7890',
        'John_Doe.jpeg');

-- Insert resume data
INSERT INTO RESUMES (user_id, resume_data)

VALUES ((SELECT id FROM USERS WHERE email = 'john.doe@example.com'),
        '{
          "networks": [
            {
              "referenceName": "LINKEDIN",
              "link": "https://linkedin.com/in/johndoe"
            },
            {
              "referenceName": "GIT",
              "link": "https://github.com/johndoe"
            }
          ],
          "educations": [
            {
              "school": "University of XYZ",
              "field": "Computer Science",
              "degree": "Bachelor''s",
              "startDate": "2020-01-01",
              "endDate": "2024-01-01",
              "duration": 4,
              "summary": "Graduated with honors"
            }
          ],
          "workExperiences": [
            {
              "company": "ABC Inc.",
              "companyCity": "New York",
              "companyLink": "https://abcinc.com",
              "occupiedPosition": "Software Engineer",
              "startDate": "2024-02-01",
              "endDate": "2025-02-01",
              "duration": 1,
              "summary": "Developed cutting-edge software"
            }
          ],
          "technicalExperiences": [
            {
              "topic": "PROGRAMMING",
              "details": [
                {
                  "name": "Java",
                  "level": 5
                },
                {
                  "name": "JavaScript",
                  "level": 4
                }
              ]
            }
          ],
          "tools": [
            "Git",
            "Jira",
            "Webpack",
            "TDD",
            "MVC"
          ],
          "methodologies": [
            "Agile",
            "Scrum"
          ],
          "skills": [
            "SQL",
            "Firebase",
            "Algorithm"
          ],
          "hobbiesAndInterest": [
            "Sport",
            "Reading",
            "Playing the Piano",
            "DIY (Do It Yourself)",
            "Travel"
          ],
          "trainingsAndCertifications": [
            "Google Cloud",
            "Clean Code"
          ]
        }' FORMAT JSON);