create table users
(
    relevant_experience_years integer,
    id                        bigint generated by default as identity,
    email                     varchar(255) unique,
    first_name                varchar(255),
    image_path                varchar(255),
    last_name                 varchar(255),
    location                  varchar(255),
    mobile_phone_number       varchar(255),
    nationality               varchar(255),
    objectives                varchar(255),
    password                  varchar(255),
    profession                varchar(255),
    summary                   varchar(255),
    data                      json,
    primary key (id)
)
