name: "Dev Workflow"
on:
  push:
    branches:
      - main
      - dev

permissions: read-all

jobs:
  test:
    name: Unit-Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Maven Package
        run: mvn -B clean package
      - name: Maven Verify and Test
        run: mvn -B verify -DskipTests=false